[2017-08-14 23:11:37,743] Making new env: CartPole-v0
gp_pole4.py:154: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
gp_pole4.py:154: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
[2017-08-15 15:54:15,559] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
